STAGES.push(
  { id: 201, subject: "linear", name: "矩阵与行列式", en: "Matrices & Determinants", code: "01", goal: "掌握矩阵运算、行列式与秩的基本性质。", weeks: "第 1-6 周", color: "#0e7c6b", topics: ["矩阵", "行列式", "逆矩阵", "秩"] },
  { id: 202, subject: "linear", name: "向量与线性方程组", en: "Vectors & Linear Systems", code: "02", goal: "用向量空间语言理解线性方程组的解。", weeks: "第 7-12 周", color: "#2e6f8f", topics: ["向量", "线性相关", "基与维数", "高斯消元"] },
  { id: 203, subject: "linear", name: "特征值与二次型", en: "Eigenvalues & Quadratic Forms", code: "03", goal: "研究矩阵的内在结构和二次型化简。", weeks: "第 13-18 周", color: "#a97d12", topics: ["特征值", "特征向量", "对角化", "二次型"] },
  { id: 204, subject: "linear", name: "线性空间与变换", en: "Spaces & Transformations", code: "04", goal: "把线性代数提升到抽象空间与映射层面。", weeks: "第 19-24 周", color: "#c94f2b", topics: ["线性空间", "线性变换", "核", "像"] }
);

TERMS.push(
  { id: "matrix", subject: "linear", term: "矩阵", en: "Matrix", stage: 201, cat: "矩阵", diff: 1, def: "按行列排列的矩形数表，用于表示线性关系和变换。", example: "[[1,2],[3,4]] 是一个 2×2 矩阵。", tip: "矩阵是数表，运算有固定规则。", related: ["determinant", "identity_matrix", "rank"] },
  { id: "determinant", subject: "linear", term: "行列式", en: "Determinant", stage: 201, cat: "矩阵", diff: 1, def: "对方阵定义的标量，衡量矩阵是否可逆和体积缩放。", example: "二阶行列式 ad-bc 等于 0 时矩阵不可逆。", tip: "行列式只对方阵有意义。", related: ["matrix", "cramer_rule", "rank"] },
  { id: "identity_matrix", subject: "linear", term: "单位矩阵", en: "Identity Matrix", stage: 201, cat: "矩阵", diff: 1, def: "主对角线为 1、其余为 0 的方阵，是矩阵乘法的单位元。", example: "A·I = I·A = A。", tip: "单位矩阵像数字乘法里的 1。", related: ["matrix", "inverse_matrix", "transpose"] },
  { id: "inverse_matrix", subject: "linear", term: "逆矩阵", en: "Inverse Matrix", stage: 201, cat: "矩阵", diff: 2, def: "与原矩阵相乘得到单位矩阵的矩阵。", example: "若 AB=I，则 B 是 A 的逆矩阵。", tip: "行列式不为 0 才存在逆矩阵。", related: ["matrix", "determinant", "elementary_transformation"] },
  { id: "transpose", subject: "linear", term: "转置", en: "Transpose", stage: 201, cat: "矩阵", diff: 1, def: "把矩阵的行与列互换得到的矩阵。", example: "[[1,2],[3,4]] 的转置是 [[1,3],[2,4]]。", tip: "转置不改变主对角线。", related: ["matrix", "inner_product", "orthogonal"] },
  { id: "rank", subject: "linear", term: "秩", en: "Rank", stage: 201, cat: "矩阵", diff: 2, def: "矩阵中线性无关的行或列的最大数目。", example: "秩为 2 说明矩阵真正只承载两维信息。", tip: "秩等于行阶梯形中非零行数。", related: ["matrix", "elementary_transformation", "linear_dependence"] },
  { id: "elementary_transformation", subject: "linear", term: "初等变换", en: "Elementary Operations", stage: 201, cat: "矩阵", diff: 1, def: "交换行、倍乘行、行加减等保持方程解不变的变换。", example: "两行互换后再消元，可把矩阵化为阶梯形。", tip: "初等变换是高斯消元的操作基础。", related: ["matrix", "rank", "gaussian_elimination"] },
  { id: "vector", subject: "linear", term: "向量", en: "Vector", stage: 202, cat: "向量", diff: 1, def: "既有大小又有方向的量，可用有序数组表示。", example: "(1,2,3) 表示三维空间中的一个向量。", tip: "向量可以相加、数乘，也可以线性组合。", related: ["linear_combination", "linear_dependence", "inner_product"] },
  { id: "linear_combination", subject: "linear", term: "线性组合", en: "Linear Combination", stage: 202, cat: "向量", diff: 1, def: "若干个向量分别乘系数后相加得到的向量。", example: "2(1,0)+3(0,1)=(2,3)。", tip: "线性组合是构造新向量的基本方式。", related: ["vector", "span", "linear_dependence"] },
  { id: "linear_dependence", subject: "linear", term: "线性相关", en: "Linear Dependence", stage: 202, cat: "向量", diff: 2, def: "某个向量可以写成其他向量的线性组合。", example: "向量 (1,2) 与 (2,4) 线性相关。", tip: "线性相关意味着存在非平凡零组合。", related: ["vector", "linear_combination", "basis"] },
  { id: "span", subject: "linear", term: "张成", en: "Span", stage: 202, cat: "向量", diff: 2, def: "一组向量所有线性组合构成的空间。", example: "两个不共线向量在平面中张成整个平面。", tip: "张成描述“能到达哪些向量”。", related: ["vector", "linear_combination", "basis"] },
  { id: "basis", subject: "linear", term: "基", en: "Basis", stage: 202, cat: "向量", diff: 2, def: "能张成空间且线性无关的一组向量。", example: "{(1,0),(0,1)} 是 R² 的一组标准基。", tip: "基中的向量既不多也不少。", related: ["span", "dimension", "linear_dependence"] },
  { id: "dimension", subject: "linear", term: "维数", en: "Dimension", stage: 202, cat: "向量", diff: 2, def: "空间中一组基所含向量的个数。", example: "R³ 的维数是 3。", tip: "同一空间的不同基个数相同。", related: ["basis", "span", "linear_transformation"] },
  { id: "linear_equation_system", subject: "linear", term: "线性方程组", en: "Linear System", stage: 202, cat: "方程组", diff: 1, def: "由若干个一次方程组成的方程组。", example: "x+y=3, x-y=1 是二元线性方程组。", tip: "线性方程组的解可用矩阵表示。", related: ["gaussian_elimination", "solution_set", "homogeneous_system"] },
  { id: "gaussian_elimination", subject: "linear", term: "高斯消元", en: "Gaussian Elimination", stage: 202, cat: "方程组", diff: 2, def: "通过初等变换把增广矩阵化为阶梯形来求解。", example: "把增广矩阵化成行阶梯形后可直接回代。", tip: "消元过程保持解集不变。", related: ["elementary_transformation", "linear_equation_system", "rank"] },
  { id: "homogeneous_system", subject: "linear", term: "齐次方程组", en: "Homogeneous System", stage: 202, cat: "方程组", diff: 2, def: "所有方程常数项都为 0 的线性方程组。", example: "Ax=0 一定有零解，可能有非零解。", tip: "非零解存在等价于列向量线性相关。", related: ["linear_equation_system", "solution_set", "kernel"] },
  { id: "solution_set", subject: "linear", term: "解集", en: "Solution Set", stage: 202, cat: "方程组", diff: 2, def: "满足方程组的所有解构成的集合。", example: "两个平面的交线就是二元线性方程组的解集。", tip: "通解 = 特解 + 齐次方程解。", related: ["linear_equation_system", "homogeneous_system", "rank"] },
  { id: "eigenvalue", subject: "linear", term: "特征值", en: "Eigenvalue", stage: 203, cat: "特征", diff: 2, def: "方阵作用后只伸缩不改变方向的非零向量对应的伸缩系数。", example: "若 Av=λv，则 λ 是特征值，v 是特征向量。", tip: "特征值描述矩阵的“固有尺度”。", related: ["eigenvector", "characteristic_polynomial", "diagonalization"] },
  { id: "eigenvector", subject: "linear", term: "特征向量", en: "Eigenvector", stage: 203, cat: "特征", diff: 2, def: "被矩阵作用后方向不变、只发生伸缩的非零向量。", example: "单位矩阵的所有非零向量都是特征向量。", tip: "特征向量定义中 v≠0。", related: ["eigenvalue", "diagonalization", "kernel"] },
  { id: "characteristic_polynomial", subject: "linear", term: "特征多项式", en: "Characteristic Polynomial", stage: 203, cat: "特征", diff: 3, def: "由 |A-λI|=0 得到的关于 λ 的多项式，其根是特征值。", example: "二阶矩阵的特征多项式一般是 λ² - (a+d)λ + (ad-bc)。", tip: "特征值的和等于迹，积等于行列式。", related: ["eigenvalue", "diagonalization", "determinant"] },
  { id: "diagonalization", subject: "linear", term: "对角化", en: "Diagonalization", stage: 203, cat: "特征", diff: 3, def: "把矩阵表示为 P⁻¹AP=D 的形式，其中 D 是对角矩阵。", example: "对称矩阵通常可以正交对角化。", tip: "有 n 个线性无关特征向量才能对角化。", related: ["eigenvalue", "eigenvector", "characteristic_polynomial"] },
  { id: "quadratic_form", subject: "linear", term: "二次型", en: "Quadratic Form", stage: 203, cat: "特征", diff: 3, def: "由向量通过对称矩阵定义的二次齐次函数。", example: "f(x,y)=ax²+2bxy+cy² 是二次型。", tip: "二次型可通过正交变换化为标准形。", related: ["matrix", "diagonalization", "eigenvalue"] },
  { id: "inner_product", subject: "linear", term: "内积", en: "Inner Product", stage: 203, cat: "几何", diff: 2, def: "衡量两个向量夹角和长度的运算。", example: "(1,2)·(3,4)=1×3+2×4=11。", tip: "内积为 0 表示两个向量正交。", related: ["vector", "orthogonal", "basis"] },
  { id: "orthogonal", subject: "linear", term: "正交", en: "Orthogonal", stage: 203, cat: "几何", diff: 2, def: "两个向量内积为 0，即夹角为 90°。", example: "(1,0) 与 (0,1) 正交。", tip: "正交向量组是很有用的基。", related: ["inner_product", "basis", "diagonalization"] },
  { id: "linear_transformation", subject: "linear", term: "线性变换", en: "Linear Transformation", stage: 204, cat: "空间", diff: 2, def: "保持向量加法和数乘的映射，通常用矩阵表示。", example: "旋转、投影都是线性变换。", tip: "线性变换由其在基上的作用完全决定。", related: ["kernel", "image", "basis"] },
  { id: "kernel", subject: "linear", term: "核", en: "Kernel", stage: 204, cat: "空间", diff: 3, def: "被线性变换映射到零向量的所有向量组成的子空间。", example: "核中的向量经过变换后消失为零。", tip: "核越大，变换越“压缩”信息。", related: ["linear_transformation", "image", "homogeneous_system"] },
  { id: "image", subject: "linear", term: "像", en: "Image", stage: 204, cat: "空间", diff: 3, def: "线性变换作用在整个空间后得到的集合。", example: "投影到 x 轴的变换，像就是 x 轴。", tip: "像的维数等于矩阵的秩。", related: ["linear_transformation", "kernel", "span"] },
  { id: "cramer_rule", subject: "linear", term: "克拉默法则", en: "Cramer's Rule", stage: 204, cat: "方程组", diff: 3, def: "用行列式比表示线性方程组唯一解的方法。", example: "x = Dx/D，其中 D 是系数行列式。", tip: "系数矩阵可逆时才适用。", related: ["determinant", "linear_equation_system", "inverse_matrix"] }
);
