const SUBJECTS = [
  { id: "econ", name: "经济学", en: "Economics", code: "01", color: "#c94f2b", desc: "稀缺、选择、供需与市场运行。", default: true },
  { id: "math", name: "高等数学", en: "Calculus", code: "02", color: "#2e6f8f", desc: "极限、导数、积分与级数。", default: false },
  { id: "linear", name: "线性代数", en: "Linear Algebra", code: "03", color: "#0e7c6b", desc: "矩阵、向量、行列式与线性空间。", default: false },
  { id: "english", name: "大学英语", en: "College English", code: "04", color: "#a97d12", desc: "高频词汇、写作与学术表达。", default: false },
  { id: "cs", name: "计算机基础", en: "Computer Science", code: "05", color: "#7a5aa6", desc: "程序设计、数据结构与计算机系统。", default: false },
  { id: "music", name: "基本乐理", en: "Music Theory", code: "06", color: "#b3558e", desc: "音高、节奏、音程、和弦与调式。", default: false }
];

let STAGES = [
  {
    id: 1,
    subject: "econ",
    name: "概念地基",
    en: "Foundations",
    code: "01",
    goal: "建立经济学的第一套语言：稀缺、选择、供需与交易。",
    weeks: "第 1-8 周",
    color: "#c94f2b",
    topics: ["稀缺与选择", "需求与供给", "弹性", "贸易"]
  },
  {
    id: 2,
    subject: "econ",
    name: "微观经济学",
    en: "Microeconomics",
    code: "02",
    goal: "理解个人与企业如何做选择，以及市场如何运转和失灵。",
    weeks: "第 9-20 周",
    color: "#0e7c6b",
    topics: ["消费者行为", "厂商成本", "市场结构", "市场失灵"]
  },
  {
    id: 3,
    subject: "econ",
    name: "宏观经济学",
    en: "Macroeconomics",
    code: "03",
    goal: "从整体视角看产出、物价、就业与政策工具。",
    weeks: "第 21-34 周",
    color: "#2e6f8f",
    topics: ["GDP 与物价", "失业与增长", "财政货币", "开放经济"]
  },
  {
    id: 4,
    subject: "econ",
    name: "进阶与拓展",
    en: "Advanced",
    code: "04",
    goal: "进入博弈、行为、发展与制度等更广阔的思考领域。",
    weeks: "第 35 周以后",
    color: "#a97d12",
    topics: ["博弈与行为", "发展与增长", "制度与信息", "前沿话题"]
  }
];

let TERMS = [
  {
    id: "scarcity",
    subject: "econ",
    term: "稀缺性",
    en: "Scarcity",
    stage: 1,
    cat: "基础概念",
    diff: 1,
    def: "资源有限，欲望无穷；稀缺让选择成为必然。",
    example: "图书馆座位有限，想坐窗边就要早去，这就是稀缺。",
    tip: "稀缺不是东西少，而是欲望更多。",
    related: ["opportunity_cost", "tradeoff", "ppf"]
  },
  {
    id: "opportunity_cost",
    subject: "econ",
    term: "机会成本",
    en: "Opportunity Cost",
    stage: 1,
    cat: "基础概念",
    diff: 1,
    def: "做一个选择时，所放弃的其他选项中价值最高的那个。",
    example: "周末去兼职赚 200 元，代价是少复习两小时，那两小时可能的提升就是机会成本。",
    tip: "机会成本不等于所有放弃选项之和，只算价值最高的那个。",
    related: ["scarcity", "tradeoff", "sunk_cost"]
  },
  {
    id: "tradeoff",
    subject: "econ",
    term: "权衡取舍",
    en: "Trade-off",
    stage: 1,
    cat: "基础概念",
    diff: 1,
    def: "因为资源有限，得到一样东西通常必须放弃另一样东西。",
    example: "用生活费买球鞋，就少了买书的预算。",
    tip: "经济学几乎所有问题都在讨论权衡取舍。",
    related: ["scarcity", "opportunity_cost", "ppf"]
  },
  {
    id: "margin",
    subject: "econ",
    term: "边际",
    en: "Margin",
    stage: 1,
    cat: "决策方法",
    diff: 1,
    def: "多增加或减少一个单位所带来的变化，决策应关注边际量。",
    example: "再吃一口是否值得，取决于这一口的满足感，而不是前面所有口。",
    tip: "别问总不总，问‘再一个’怎么样。",
    related: ["diminishing_marginal_utility", "marginal_cost", "rational_agent"]
  },
  {
    id: "rational_agent",
    subject: "econ",
    term: "理性人假设",
    en: "Rational Agent",
    stage: 1,
    cat: "基础概念",
    diff: 1,
    def: "假设人们会在信息与约束下，系统比较收益和成本来做出最有利的选择。",
    example: "买奶茶前比较价格和热量，就是在做理性权衡。",
    tip: "理性不等于聪明，只代表有目标地做选择。",
    related: ["margin", "utility", "behavioral_economics"]
  },
  {
    id: "utility",
    subject: "econ",
    term: "效用",
    en: "Utility",
    stage: 1,
    cat: "消费者理论",
    diff: 1,
    def: "消费或拥有某种东西带来的主观满足程度。",
    example: "同样是 100 元，有人买书更满足，有人买游戏更满足。",
    tip: "效用无法用统一单位测量，但可以比较大小。",
    related: ["rational_agent", "diminishing_marginal_utility", "indifference_curve"]
  },
  {
    id: "demand",
    subject: "econ",
    term: "需求",
    en: "Demand",
    stage: 1,
    cat: "市场机制",
    diff: 1,
    def: "在其他条件不变时，消费者在每个价格下愿意且能够购买的数量。",
    example: "奶茶 8 元时每天买一杯，12 元时改买别的饮料。",
    tip: "需求是价格和数量的整条关系，不是某一个购买量。",
    related: ["supply", "equilibrium", "law_of_demand", "shift_along"]
  },
  {
    id: "supply",
    subject: "econ",
    term: "供给",
    en: "Supply",
    stage: 1,
    cat: "市场机制",
    diff: 1,
    def: "在其他条件不变时，生产者在每个价格下愿意且能够出售的数量。",
    example: "鸡蛋价格高时，养鸡场愿意卖更多鸡蛋。",
    tip: "供给和需求一样，都描述‘每个价格下的量’。",
    related: ["demand", "equilibrium", "law_of_supply", "marginal_cost"]
  },
  {
    id: "equilibrium",
    subject: "econ",
    term: "市场均衡",
    en: "Market Equilibrium",
    stage: 1,
    cat: "市场机制",
    diff: 1,
    def: "需求量等于供给量时的状态，此时价格没有继续变动的压力。",
    example: "当奶茶 8 元时刚好卖完且不多不少，就接近均衡。",
    tip: "均衡是供需两条线相交的点。",
    related: ["demand", "supply", "total_surplus"]
  },
  {
    id: "law_of_demand",
    subject: "econ",
    term: "需求定律",
    en: "Law of Demand",
    stage: 1,
    cat: "市场机制",
    diff: 1,
    def: "其他条件不变，价格越高，需求量越少。",
    example: "电影票涨价后，选择去看的人变少。",
    tip: "价格与需求量沿着需求曲线反向移动。",
    related: ["demand", "elasticity", "shift_along"]
  },
  {
    id: "law_of_supply",
    subject: "econ",
    term: "供给定律",
    en: "Law of Supply",
    stage: 1,
    cat: "市场机制",
    diff: 1,
    def: "其他条件不变，价格越高，供给量越多。",
    example: "口罩需求大涨、价格上升后，工厂更愿意增产。",
    tip: "价格与供给量沿着供给曲线同向移动。",
    related: ["supply", "elasticity", "marginal_cost"]
  },
  {
    id: "elasticity",
    subject: "econ",
    term: "弹性",
    en: "Elasticity",
    stage: 1,
    cat: "市场机制",
    diff: 2,
    def: "一个变量对另一个变量变化的反应程度，用百分比变化之比衡量。",
    example: "油价微涨，通勤量几乎不变，说明短期通勤需求弹性小。",
    tip: "弹性是‘敏感度’，不只看方向，更看程度。",
    related: ["law_of_demand", "substitutes_complements", "demand"]
  },
  {
    id: "substitutes_complements",
    subject: "econ",
    term: "替代品与互补品",
    en: "Substitutes & Complements",
    stage: 1,
    cat: "消费者理论",
    diff: 2,
    def: "替代品可以互相替换；互补品通常一起使用。",
    example: "可乐和雪碧是替代品，手机和充电器是互补品。",
    tip: "替代品价格涨，替代需求升；互补品价格涨，彼此需求降。",
    related: ["elasticity", "demand", "normal_inferior"]
  },
  {
    id: "normal_inferior",
    subject: "econ",
    term: "正常品与低档品",
    en: "Normal & Inferior Goods",
    stage: 1,
    cat: "消费者理论",
    diff: 2,
    def: "收入增加时买得更多的是正常品；买得更少的是低档品。",
    example: "工资涨了换更贵的餐厅，方便面这类商品可能买得更少。",
    tip: "判断标准是收入变化后需求量同向还是反向。",
    related: ["demand", "substitutes_complements", "budget_constraint"]
  },
  {
    id: "comparative_advantage",
    subject: "econ",
    term: "比较优势",
    en: "Comparative Advantage",
    stage: 1,
    cat: "贸易",
    diff: 2,
    def: "以更低的机会成本生产某样东西的能力。",
    example: "你打字快又擅长排版，排版对朋友来说更贵，就由你来做。",
    tip: "比较优势看相对成本，不是看谁绝对更强。",
    related: ["opportunity_cost", "trade", "ppf"]
  },
  {
    id: "trade",
    subject: "econ",
    term: "贸易",
    en: "Trade",
    stage: 1,
    cat: "贸易",
    diff: 1,
    def: "自愿的交换让双方都能按各自优势专业分工，并从中获益。",
    example: "北方用苹果换南方大米，各取所需且都更便宜。",
    tip: "只要机会成本不同，交换就能创造额外价值。",
    related: ["comparative_advantage", "trade_balance", "exchange_rate"]
  },
  {
    id: "ppf",
    subject: "econ",
    term: "生产可能性边界",
    en: "Production Possibilities Frontier",
    stage: 1,
    cat: "基础概念",
    diff: 2,
    def: "在资源和技术既定时，能生产的两种产品最大组合的曲线。",
    example: "一块地要么种玉米要么种大豆，边界外的组合做不到。",
    tip: "边界弯曲说明机会成本递增，边界移动说明增长。",
    related: ["scarcity", "opportunity_cost", "economic_growth"]
  },
  {
    id: "shift_along",
    subject: "econ",
    term: "需求变动与需求量变动",
    en: "Shift vs. Movement",
    stage: 1,
    cat: "市场机制",
    diff: 2,
    def: "价格变化引起沿线移动；其他因素变化引起整条曲线平移。",
    example: "降价导致买更多是沿线移动；收入上涨导致每个价格都多买是曲线平移。",
    tip: "看见‘价格’走曲线，看见‘其他条件’移曲线。",
    related: ["demand", "law_of_demand", "equilibrium"]
  },
  {
    id: "consumer_surplus",
    subject: "econ",
    term: "消费者剩余",
    en: "Consumer Surplus",
    stage: 2,
    cat: "福利分析",
    diff: 2,
    def: "消费者愿意支付的最高价与实际支付价的差额，代表交易中获得的净好处。",
    example: "你愿花 50 元买票，实际 30 元，剩余就是 20 元。",
    tip: "剩余越大，消费者越划算。",
    related: ["producer_surplus", "total_surplus", "demand"]
  },
  {
    id: "producer_surplus",
    subject: "econ",
    term: "生产者剩余",
    en: "Producer Surplus",
    stage: 2,
    cat: "福利分析",
    diff: 2,
    def: "生产者实际收到的价格与愿意接受的最低价格之差。",
    example: "成本 25 元的包卖 35 元，生产者剩余 10 元。",
    tip: "卖方的‘赚头’就是生产者剩余。",
    related: ["consumer_surplus", "total_surplus", "supply"]
  },
  {
    id: "total_surplus",
    subject: "econ",
    term: "总剩余",
    en: "Total Surplus",
    stage: 2,
    cat: "福利分析",
    diff: 2,
    def: "消费者剩余与生产者剩余之和，衡量市场交易创造的总福利。",
    example: "均衡价格下双方剩余总和最大，说明市场有效率。",
    tip: "总剩余最大化常被当作‘蛋糕最大’。",
    related: ["consumer_surplus", "producer_surplus", "equilibrium"]
  },
  {
    id: "indifference_curve",
    subject: "econ",
    term: "无差异曲线",
    en: "Indifference Curve",
    stage: 2,
    cat: "消费者理论",
    diff: 3,
    def: "带给消费者相同效用水平的两种商品组合的轨迹。",
    example: "一个苹果加两个香蕉，与两个苹果加一个香蕉，你可能觉得一样满足。",
    tip: "曲线越远离原点，效用越高。",
    related: ["utility", "budget_constraint", "diminishing_marginal_utility"]
  },
  {
    id: "budget_constraint",
    subject: "econ",
    term: "预算约束线",
    en: "Budget Constraint",
    stage: 2,
    cat: "消费者理论",
    diff: 2,
    def: "在收入和价格既定时，消费者能买得起的商品组合边界。",
    example: "每月 1000 元，奶茶 30 元一杯或面包 10 元一个，边界内都可负担。",
    tip: "收入增加线外移，价格变化线转动。",
    related: ["indifference_curve", "normal_inferior", "utility"]
  },
  {
    id: "diminishing_marginal_utility",
    subject: "econ",
    term: "边际效用递减",
    en: "Diminishing Marginal Utility",
    stage: 2,
    cat: "消费者理论",
    diff: 2,
    def: "连续消费同一商品时，每增加一单位带来的额外满足通常逐渐减少。",
    example: "第一杯奶茶很幸福，第三杯时幸福感明显下降。",
    tip: "不是不喜欢，是‘再来一个’越来越不诱人。",
    related: ["utility", "margin", "indifference_curve"]
  },
  {
    id: "explicit_implicit_cost",
    subject: "econ",
    term: "显性成本与隐性成本",
    en: "Explicit & Implicit Costs",
    stage: 2,
    cat: "厂商成本",
    diff: 2,
    def: "显性成本是实际支付的支出，隐性成本是不发生现金支付但放弃的机会。",
    example: "开店付房租是显性成本，老板放弃的工资是隐性成本。",
    tip: "经济学成本两者都算，会计成本通常只算显性。",
    related: ["opportunity_cost", "fixed_variable_cost", "marginal_cost"]
  },
  {
    id: "fixed_variable_cost",
    subject: "econ",
    term: "固定成本与可变成本",
    en: "Fixed & Variable Costs",
    stage: 2,
    cat: "厂商成本",
    diff: 2,
    def: "固定成本不随产量变化，可变成本随产量变化。",
    example: "厂房租金是固定成本，原料与加班工资是可变成本。",
    tip: "短期的‘固定’在长期也能改变。",
    related: ["marginal_cost", "average_cost", "economies_of_scale"]
  },
  {
    id: "marginal_cost",
    subject: "econ",
    term: "边际成本",
    en: "Marginal Cost",
    stage: 2,
    cat: "厂商成本",
    diff: 2,
    def: "多生产一单位产品所增加的总成本。",
    example: "再做第 101 杯奶茶，多花的原料和人工就是边际成本。",
    tip: "定价与产量决策都看边际成本。",
    related: ["margin", "average_cost", "supply"]
  },
  {
    id: "average_cost",
    subject: "econ",
    term: "平均成本",
    en: "Average Cost",
    stage: 2,
    cat: "厂商成本",
    diff: 2,
    def: "总成本除以产量，即每一单位产品平均分摊的成本。",
    example: "总成本 1000 元生产 200 杯，平均成本 5 元。",
    tip: "平均成本下降可能是规模效应，上升可能是瓶颈。",
    related: ["fixed_variable_cost", "marginal_cost", "economies_of_scale"]
  },
  {
    id: "economies_of_scale",
    subject: "econ",
    term: "规模经济",
    en: "Economies of Scale",
    stage: 2,
    cat: "厂商成本",
    diff: 2,
    def: "产量扩大使平均成本下降的现象。",
    example: "工厂多生产面包，分摊下来的烤箱和租金成本更低。",
    tip: "规模经济的关键是固定成本被摊薄。",
    related: ["average_cost", "fixed_variable_cost", "monopoly"]
  },
  {
    id: "perfect_competition",
    subject: "econ",
    term: "完全竞争",
    en: "Perfect Competition",
    stage: 2,
    cat: "市场结构",
    diff: 2,
    def: "大量买家和卖家、产品同质、自由进出，单个企业是价格接受者的市场。",
    example: "农产品市场接近完全竞争，小农户无法单独影响粮价。",
    tip: "完全竞争下长期经济利润趋于零。",
    related: ["monopoly", "monopolistic_competition", "oligopoly"]
  },
  {
    id: "monopoly",
    subject: "econ",
    term: "垄断",
    en: "Monopoly",
    stage: 2,
    cat: "市场结构",
    diff: 2,
    def: "市场上只有一个卖家，能通过控制产量影响价格。",
    example: "某些城市只有一家自来水公司。",
    tip: "垄断者按边际收益等于边际成本定价，价格高于边际成本。",
    related: ["perfect_competition", "oligopoly", "market_failure"]
  },
  {
    id: "monopolistic_competition",
    subject: "econ",
    term: "垄断竞争",
    en: "Monopolistic Competition",
    stage: 2,
    cat: "市场结构",
    diff: 2,
    def: "许多卖家提供略有差异的产品，各自有一点定价能力。",
    example: "奶茶店很多，但每家口味和品牌略有不同。",
    tip: "差异带来定价权，进入自由又让利润长期趋零。",
    related: ["perfect_competition", "monopoly", "oligopoly"]
  },
  {
    id: "oligopoly",
    subject: "econ",
    term: "寡头",
    en: "Oligopoly",
    stage: 2,
    cat: "市场结构",
    diff: 2,
    def: "少数几家大企业主导市场，彼此决策相互影响。",
    example: "手机操作系统、航空公司和大型电商都接近寡头。",
    tip: "寡头之间既有竞争也可能默契合谋。",
    related: ["monopoly", "game_theory", "nash_equilibrium"]
  },
  {
    id: "price_discrimination",
    subject: "econ",
    term: "价格歧视",
    en: "Price Discrimination",
    stage: 2,
    cat: "厂商行为",
    diff: 3,
    def: "对同样的产品向不同买家收取不同价格。",
    example: "学生票、早鸟票、会员价都常使用价格歧视。",
    tip: "成功的前提是能区分顾客且防止转售。",
    related: ["monopoly", "consumer_surplus", "producer_surplus"]
  },
  {
    id: "externality",
    subject: "econ",
    term: "外部性",
    en: "Externality",
    stage: 2,
    cat: "市场失灵",
    diff: 2,
    def: "一个人的行为给他人带来未通过价格补偿的成本或收益。",
    example: "工厂排污影响邻居是负外部性；种花让路人愉悦是正外部性。",
    tip: "外部性让私人成本与社会成本分离。",
    related: ["market_failure", "coase_theorem", "tragedy_of_commons"]
  },
  {
    id: "coase_theorem",
    subject: "econ",
    term: "科斯定理",
    en: "Coase Theorem",
    stage: 2,
    cat: "市场失灵",
    diff: 3,
    def: "当产权清晰且交易成本很低时，当事人会自行协商到有效率的结果，无论产权最初给谁。",
    example: "楼上装修吵到楼下，只要赔偿规则清楚，双方能谈出安排。",
    tip: "科斯定理的前提是产权清晰、谈判成本低。",
    related: ["externality", "market_failure", "institutional_economics"]
  },
  {
    id: "public_goods",
    subject: "econ",
    term: "公共物品",
    en: "Public Goods",
    stage: 2,
    cat: "市场失灵",
    diff: 2,
    def: "具有非排他性和非竞争性的物品，一人使用不影响他人且难以收费。",
    example: "国防、路灯和广播节目都是公共物品。",
    tip: "公共物品容易引发搭便车，私人供给不足。",
    related: ["free_rider", "market_failure", "tragedy_of_commons"]
  },
  {
    id: "free_rider",
    subject: "econ",
    term: "搭便车",
    en: "Free Rider Problem",
    stage: 2,
    cat: "市场失灵",
    diff: 2,
    def: "不付出成本却享受公共物品或集体行动成果的行为。",
    example: "邻居集资装路灯，不出钱的人也能借光。",
    tip: "搭便车导致公共物品由市场提供不足。",
    related: ["public_goods", "market_failure", "externality"]
  },
  {
    id: "tragedy_of_commons",
    subject: "econ",
    term: "公地悲剧",
    en: "Tragedy of the Commons",
    stage: 2,
    cat: "市场失灵",
    diff: 2,
    def: "共享资源因每个人都按私利使用而过度消耗。",
    example: "公共牧场人人多放牧，最后草场退化。",
    tip: "解决思路是产权、配额或集体规则。",
    related: ["externality", "public_goods", "coase_theorem"]
  },
  {
    id: "information_asymmetry",
    subject: "econ",
    term: "信息不对称",
    en: "Asymmetric Information",
    stage: 2,
    cat: "市场失灵",
    diff: 2,
    def: "交易双方掌握的信息量不同，弱势一方可能吃亏。",
    example: "卖二手车的更清楚车况，买家难以判断。",
    tip: "信息不对称会扭曲价格和选择。",
    related: ["adverse_selection", "moral_hazard", "market_failure"]
  },
  {
    id: "adverse_selection",
    subject: "econ",
    term: "逆向选择",
    en: "Adverse Selection",
    stage: 2,
    cat: "市场失灵",
    diff: 3,
    def: "信息不对称下，质量差的一方更愿意进入交易，挤走好的一方。",
    example: "保险市场上，健康风险高的人更想买保险，推高保费。",
    tip: "逆向选择发生在交易之前。",
    related: ["information_asymmetry", "moral_hazard", "information_economics"]
  },
  {
    id: "moral_hazard",
    subject: "econ",
    term: "道德风险",
    en: "Moral Hazard",
    stage: 2,
    cat: "市场失灵",
    diff: 3,
    def: "一方在得到保障后减少努力或增大风险，因为成本由对方承担。",
    example: "买了全险后开车更随意，就是道德风险。",
    tip: "道德风险发生在交易之后。",
    related: ["information_asymmetry", "adverse_selection", "principal_agent"]
  },
  {
    id: "pareto_optimal",
    subject: "econ",
    term: "帕累托最优",
    en: "Pareto Optimality",
    stage: 2,
    cat: "福利分析",
    diff: 3,
    def: "在不损害任何人的情况下，已无法让某人变得更好的状态。",
    example: "教室座位按偏好交换后，没人愿意再换，就接近帕累托最优。",
    tip: "帕累托改进是不让任何人受损的改善。",
    related: ["total_surplus", "equilibrium", "market_failure"]
  },
  {
    id: "market_failure",
    subject: "econ",
    term: "市场失灵",
    en: "Market Failure",
    stage: 2,
    cat: "市场失灵",
    diff: 2,
    def: "市场自发结果偏离有效配置，通常由外部性、公共物品、垄断或信息问题引起。",
    example: "污染没人管、疫苗没人愿提供，都是市场失灵信号。",
    tip: "市场失灵常成为政府干预的理由。",
    related: ["externality", "public_goods", "monopoly", "information_asymmetry"]
  },
  {
    id: "gdp",
    subject: "econ",
    term: "GDP",
    en: "Gross Domestic Product",
    stage: 3,
    cat: "国民经济核算",
    diff: 1,
    def: "一定时期内一国境内生产的所有最终商品与服务的市场价值。",
    example: "国家一年里卖出的新车、理发、软件服务等最终产值都计入 GDP。",
    tip: "GDP 按境内统计，看最终品，不计中间品重复。",
    related: ["nominal_real_gdp", "economic_growth", "cpi"]
  },
  {
    id: "nominal_real_gdp",
    subject: "econ",
    term: "名义 GDP 与实际 GDP",
    en: "Nominal vs. Real GDP",
    stage: 3,
    cat: "国民经济核算",
    diff: 2,
    def: "名义 GDP 按当年价格计算，实际 GDP 按基期价格计算以剔除物价变化。",
    example: "GDP 涨了 10%，其中 8% 是涨价，实际增长只有约 2%。",
    tip: "比较产出增长要看实际 GDP。",
    related: ["gdp", "inflation", "economic_growth"]
  },
  {
    id: "cpi",
    subject: "econ",
    term: "消费者价格指数",
    en: "Consumer Price Index",
    stage: 3,
    cat: "物价",
    diff: 1,
    def: "衡量一篮子代表性消费品价格水平变动的指数。",
    example: "今年买同样一篮子菜比去年贵 5%，CPI 涨幅约为 5%。",
    tip: "CPI 关注消费者，不等于所有物价。",
    related: ["inflation", "gdp", "deflation"]
  },
  {
    id: "inflation",
    subject: "econ",
    term: "通货膨胀",
    en: "Inflation",
    stage: 3,
    cat: "物价",
    diff: 1,
    def: "整体物价水平持续上升，货币购买力下降。",
    example: "十年前十元能买三斤菜，现在只能买一斤多。",
    tip: "温和通胀常见，恶性通胀会摧毁储蓄。",
    related: ["cpi", "deflation", "inflation_expectations", "phillips_curve"]
  },
  {
    id: "deflation",
    subject: "econ",
    term: "通货紧缩",
    en: "Deflation",
    stage: 3,
    cat: "物价",
    diff: 2,
    def: "整体物价水平持续下降，常伴随需求疲软和债务负担加重。",
    example: "东西越来越便宜，但人们更不愿消费，企业更难赚钱。",
    tip: "通缩不等于好事，可能让经济陷入螺旋。",
    related: ["inflation", "cpi", "aggregate_demand"]
  },
  {
    id: "unemployment_rate",
    subject: "econ",
    term: "失业率",
    en: "Unemployment Rate",
    stage: 3,
    cat: "就业",
    diff: 1,
    def: "失业人数占劳动力人口的比例。",
    example: "100 个劳动力中有 5 个人在找工作但没找到，失业率为 5%。",
    tip: "不找工作的人不计入失业，只算退出劳动力。",
    related: ["unemployment_types", "natural_rate", "business_cycle"]
  },
  {
    id: "unemployment_types",
    subject: "econ",
    term: "失业类型",
    en: "Types of Unemployment",
    stage: 3,
    cat: "就业",
    diff: 2,
    def: "摩擦性、结构性与周期性失业分别来自换工作、技能错配与经济衰退。",
    example: "毕业季找工作属于摩擦性失业；工厂自动化后的技能错配是结构性；萧条裁员是周期性。",
    tip: "自然失业率约等于摩擦加结构失业。",
    related: ["unemployment_rate", "natural_rate", "business_cycle"]
  },
  {
    id: "natural_rate",
    subject: "econ",
    term: "自然失业率",
    en: "Natural Rate of Unemployment",
    stage: 3,
    cat: "就业",
    diff: 2,
    def: "经济在正常状态和长期均衡时仍存在的失业率。",
    example: "即使经济繁荣，也总有人正在换工作或技能不符。",
    tip: "周期性失业围绕自然失业率上下波动。",
    related: ["unemployment_types", "phillips_curve", "business_cycle"]
  },
  {
    id: "business_cycle",
    subject: "econ",
    term: "经济周期",
    en: "Business Cycle",
    stage: 3,
    cat: "总量经济",
    diff: 1,
    def: "经济活动在扩张与收缩之间的波动，包含繁荣、衰退、谷底和复苏。",
    example: "疫情后旅游需求暴跌再反弹，就是一个小型周期。",
    tip: "周期是波动，不是长期趋势。",
    related: ["aggregate_demand", "unemployment_types", "economic_growth"]
  },
  {
    id: "aggregate_demand",
    subject: "econ",
    term: "总需求",
    en: "Aggregate Demand",
    stage: 3,
    cat: "总量经济",
    diff: 2,
    def: "一定价格水平下，家庭、企业、政府与外国买家愿意购买的总量。",
    example: "物价普遍下降时，人们更愿意消费和投资，总需求上升。",
    tip: "总需求包括消费、投资、政府购买和净出口。",
    related: ["aggregate_supply", "fiscal_policy", "monetary_policy"]
  },
  {
    id: "aggregate_supply",
    subject: "econ",
    term: "总供给",
    en: "Aggregate Supply",
    stage: 3,
    cat: "总量经济",
    diff: 2,
    def: "一定价格水平下，经济体愿意生产的总产出。",
    example: "短期物价上升刺激企业加班增产；长期产出由技术决定。",
    tip: "长期总供给是垂直的，由生产能力决定。",
    related: ["aggregate_demand", "economic_growth", "business_cycle"]
  },
  {
    id: "fiscal_policy",
    subject: "econ",
    term: "财政政策",
    en: "Fiscal Policy",
    stage: 3,
    cat: "政策工具",
    diff: 2,
    def: "政府通过税收与支出调节总需求的政策。",
    example: "经济低迷时政府增加基建支出或减税。",
    tip: "财政政策由财政部门主导，常直接作用于总需求。",
    related: ["aggregate_demand", "crowding_out", "multiplier"]
  },
  {
    id: "monetary_policy",
    subject: "econ",
    term: "货币政策",
    en: "Monetary Policy",
    stage: 3,
    cat: "政策工具",
    diff: 2,
    def: "中央银行通过调节货币供给和利率影响经济活动。",
    example: "央行降息让贷款更便宜，刺激消费与投资。",
    tip: "货币政策通常由央行独立操作。",
    related: ["central_bank", "interest_rate", "aggregate_demand"]
  },
  {
    id: "interest_rate",
    subject: "econ",
    term: "利率",
    en: "Interest Rate",
    stage: 3,
    cat: "金融",
    diff: 1,
    def: "借钱的成本或存钱得到的回报，是资金的价格。",
    example: "房贷利率 5%，借 100 万每年利息 5 万。",
    tip: "利率下降会刺激借贷与投资。",
    related: ["monetary_policy", "money", "crowding_out"]
  },
  {
    id: "multiplier",
    subject: "econ",
    term: "乘数效应",
    en: "Multiplier Effect",
    stage: 3,
    cat: "政策工具",
    diff: 2,
    def: "一笔初始支出通过收入再消费带来多轮总需求扩张。",
    example: "政府花 1000 万修路，工人拿工资再消费，总影响可能超过 1000 万。",
    tip: "乘数大小取决于边际消费倾向。",
    related: ["fiscal_policy", "aggregate_demand", "crowding_out"]
  },
  {
    id: "crowding_out",
    subject: "econ",
    term: "挤出效应",
    en: "Crowding Out",
    stage: 3,
    cat: "政策工具",
    diff: 3,
    def: "政府借款增加推高利率，从而减少私人投资。",
    example: "政府发债太多，企业贷款变贵，投资被挤出。",
    tip: "扩张财政可能以挤占私人投资为代价。",
    related: ["fiscal_policy", "interest_rate", "multiplier"]
  },
  {
    id: "phillips_curve",
    subject: "econ",
    term: "菲利普斯曲线",
    en: "Phillips Curve",
    stage: 3,
    cat: "总量经济",
    diff: 3,
    def: "短期里通胀与失业之间的反向关系：失业低时通胀易上升。",
    example: "经济过热、招工困难，工资涨得快，物价也涨得快。",
    tip: "长期预期调整后，两者不存在稳定取舍。",
    related: ["inflation", "natural_rate", "inflation_expectations"]
  },
  {
    id: "exchange_rate",
    subject: "econ",
    term: "汇率",
    en: "Exchange Rate",
    stage: 3,
    cat: "开放经济",
    diff: 1,
    def: "一国货币兑换另一国货币的价格。",
    example: "1 美元兑 7 元人民币，就是美元对人民币的汇率。",
    tip: "本币升值使出口变贵、进口变便宜。",
    related: ["trade_balance", "trade", "central_bank"]
  },
  {
    id: "central_bank",
    subject: "econ",
    term: "中央银行",
    en: "Central Bank",
    stage: 3,
    cat: "金融",
    diff: 1,
    def: "负责发行货币、制定货币政策并维护金融稳定的机构。",
    example: "中国人民银行决定政策利率和管理人民币。",
    tip: "央行是‘银行的银行’，也是最后贷款人。",
    related: ["monetary_policy", "interest_rate", "money"]
  },
  {
    id: "money",
    subject: "econ",
    term: "货币",
    en: "Money",
    stage: 3,
    cat: "金融",
    diff: 1,
    def: "被广泛接受的交换媒介，同时承担计价单位与价值储藏职能。",
    example: "人民币是法定货币，买菜、存钱、标价都靠它。",
    tip: "货币的本质是共识，不是纸张本身。",
    related: ["central_bank", "interest_rate", "inflation"]
  },
  {
    id: "trade_balance",
    subject: "econ",
    term: "贸易差额",
    en: "Trade Balance",
    stage: 3,
    cat: "开放经济",
    diff: 1,
    def: "一国出口总额与进口总额之差。",
    example: "出口 5000 亿、进口 4000 亿，贸易顺差 1000 亿。",
    tip: "顺差不一定更好，长期失衡会带来调整压力。",
    related: ["exchange_rate", "trade", "gdp"]
  },
  {
    id: "inflation_expectations",
    subject: "econ",
    term: "通胀预期",
    en: "Inflation Expectations",
    stage: 3,
    cat: "物价",
    diff: 3,
    def: "人们对未来物价走势的预期，会反过来影响当前工资与定价。",
    example: "大家预期明年涨价，现在就要求加薪，价格真可能提前上涨。",
    tip: "预期是通胀的重要自我实现机制。",
    related: ["inflation", "phillips_curve", "rational_expectations"]
  },
  {
    id: "game_theory",
    subject: "econ",
    term: "博弈论",
    en: "Game Theory",
    stage: 4,
    cat: "博弈与行为",
    diff: 2,
    def: "研究多个决策者相互影响时的策略选择的数学框架。",
    example: "两家奶茶店决定是否降价，结果取决于对方怎么反应。",
    tip: "博弈三要素：参与者、策略、收益。",
    related: ["nash_equilibrium", "prisoners_dilemma", "dominant_strategy"]
  },
  {
    id: "nash_equilibrium",
    subject: "econ",
    term: "纳什均衡",
    en: "Nash Equilibrium",
    stage: 4,
    cat: "博弈与行为",
    diff: 3,
    def: "在别人策略既定时，每个人都没有动力单方面改变策略的组合。",
    example: "两家都维持高价时，谁单方面降价都会更亏，于是都不动。",
    tip: "纳什均衡不是最优结果，只是稳定结果。",
    related: ["game_theory", "dominant_strategy", "prisoners_dilemma"]
  },
  {
    id: "prisoners_dilemma",
    subject: "econ",
    term: "囚徒困境",
    en: "Prisoner's Dilemma",
    stage: 4,
    cat: "博弈与行为",
    diff: 2,
    def: "两人都选对自己最好的策略，结果反而对集体更差。",
    example: "两个嫌疑人各自坦白最安全，但两人都沉默对整体更好。",
    tip: "个人理性加在一起可能变成集体非理性。",
    related: ["game_theory", "dominant_strategy", "nash_equilibrium"]
  },
  {
    id: "dominant_strategy",
    subject: "econ",
    term: "占优策略",
    en: "Dominant Strategy",
    stage: 4,
    cat: "博弈与行为",
    diff: 2,
    def: "无论对方怎么做，都是自己最优选择的策略。",
    example: "在囚徒困境中，坦白对每个嫌疑人都是占优策略。",
    tip: "有占优策略时，理性人一定会选它。",
    related: ["game_theory", "nash_equilibrium", "prisoners_dilemma"]
  },
  {
    id: "auction_theory",
    subject: "econ",
    term: "拍卖理论",
    en: "Auction Theory",
    stage: 4,
    cat: "机制与信息",
    diff: 3,
    def: "研究不同拍卖规则如何影响出价与成交结果的领域。",
    example: "英式拍卖公开加价，密封拍卖只看一次出价。",
    tip: "规则不同，赢家诅咒和信息暴露也不同。",
    related: ["mechanism_design", "game_theory", "information_economics"]
  },
  {
    id: "mechanism_design",
    subject: "econ",
    term: "机制设计",
    en: "Mechanism Design",
    stage: 4,
    cat: "机制与信息",
    diff: 3,
    def: "设计游戏规则，使参与者出于自利行为达到期望结果。",
    example: "拍卖、车牌竞价和平台排序算法都涉及机制设计。",
    tip: "机制设计是‘逆向博弈论’。",
    related: ["auction_theory", "game_theory", "principal_agent"]
  },
  {
    id: "behavioral_economics",
    subject: "econ",
    term: "行为经济学",
    en: "Behavioral Economics",
    stage: 4,
    cat: "博弈与行为",
    diff: 2,
    def: "用心理学证据修正理性人假设，研究现实中的系统偏差。",
    example: "限时折扣让人冲动消费，就是行为经济学现象。",
    tip: "人不是完全理性，但偏差有规律。",
    related: ["rational_agent", "prospect_theory", "experimental_economics"]
  },
  {
    id: "prospect_theory",
    subject: "econ",
    term: "前景理论",
    en: "Prospect Theory",
    stage: 4,
    cat: "博弈与行为",
    diff: 3,
    def: "人在收益面前更保守，在损失面前更冒险，损失带来的痛感强于同等收益的快乐。",
    example: "赚 100 元的快乐，通常小于亏 100 元的痛苦。",
    tip: "参考点决定你是感觉‘赚’还是‘亏’。",
    related: ["behavioral_economics", "sunk_cost", "rational_agent"]
  },
  {
    id: "sunk_cost",
    subject: "econ",
    term: "沉没成本",
    en: "Sunk Cost",
    stage: 4,
    cat: "决策方法",
    diff: 1,
    def: "已经付出且无法收回的成本，做决定时不应再考虑。",
    example: "电影票买完不好看，继续硬看才是真的浪费。",
    tip: "沉没成本不是机会成本，别让它绑架选择。",
    related: ["opportunity_cost", "prospect_theory", "margin"]
  },
  {
    id: "gini_coefficient",
    subject: "econ",
    term: "基尼系数",
    en: "Gini Coefficient",
    stage: 4,
    cat: "发展与分配",
    diff: 2,
    def: "衡量收入或财富分配不平等程度的指标，0 为完全平等，1 为完全不平等。",
    example: "基尼系数 0.4 左右通常被认为需要关注分配问题。",
    tip: "系数越大，分配越不均。",
    related: ["lorenz_curve", "poverty_trap", "economic_growth"]
  },
  {
    id: "lorenz_curve",
    subject: "econ",
    term: "洛伦兹曲线",
    en: "Lorenz Curve",
    stage: 4,
    cat: "发展与分配",
    diff: 2,
    def: "累计人口与累计收入关系的曲线，越偏离对角线越不平等。",
    example: "最穷的 20% 人口只拿 5% 收入，曲线会明显下凹。",
    tip: "对角线代表绝对平等。",
    related: ["gini_coefficient", "poverty_trap", "institutional_economics"]
  },
  {
    id: "poverty_trap",
    subject: "econ",
    term: "贫困陷阱",
    en: "Poverty Trap",
    stage: 4,
    cat: "发展与分配",
    diff: 2,
    def: "贫困使人无法积累资本，缺乏资本又让人难以摆脱贫困的循环。",
    example: "每天收入刚好吃饭，没有余钱上学或投资。",
    tip: "打破循环常需要外部一次大推力。",
    related: ["human_capital", "economic_growth", "gini_coefficient"]
  },
  {
    id: "human_capital",
    subject: "econ",
    term: "人力资本",
    en: "Human Capital",
    stage: 4,
    cat: "发展与增长",
    diff: 1,
    def: "体现在人身上的知识、技能与健康，能提高生产能力。",
    example: "上大学、学编程和保持锻炼都是在积累人力资本。",
    tip: "人力资本是经济增长的重要引擎。",
    related: ["economic_growth", "poverty_trap", "solow_model"]
  },
  {
    id: "economic_growth",
    subject: "econ",
    term: "经济增长",
    en: "Economic Growth",
    stage: 4,
    cat: "发展与增长",
    diff: 1,
    def: "一国长期内生产能力的提升，通常用实际人均 GDP 增长衡量。",
    example: "新技术让同样资源生产出更多产品，人均产出上升。",
    tip: "增长来自要素积累与生产率提高。",
    related: ["gdp", "human_capital", "solow_model"]
  },
  {
    id: "solow_model",
    subject: "econ",
    term: "索洛模型",
    en: "Solow Model",
    stage: 4,
    cat: "发展与增长",
    diff: 3,
    def: "解释资本积累、人口增长与技术进步如何共同决定长期增长的新古典模型。",
    example: "投入更多机器能短期增长，长期增长主要靠技术进步。",
    tip: "资本有边际递减，技术是长期增长的关键。",
    related: ["economic_growth", "human_capital", "ppf"]
  },
  {
    id: "institutional_economics",
    subject: "econ",
    term: "制度经济学",
    en: "Institutional Economics",
    stage: 4,
    cat: "制度与信息",
    diff: 2,
    def: "研究法律、产权、习俗等制度如何塑造经济激励与结果。",
    example: "产权保护越好，创业者越敢投资。",
    tip: "制度是‘游戏规则’，决定激励。",
    related: ["coase_theorem", "information_economics", "economic_growth"]
  },
  {
    id: "information_economics",
    subject: "econ",
    term: "信息经济学",
    en: "Information Economics",
    stage: 4,
    cat: "制度与信息",
    diff: 3,
    def: "研究信息不对称、信号与筛选如何影响市场行为的领域。",
    example: "文凭是求职中的信号，帮雇主筛掉低能力者。",
    tip: "信号要可信，模仿成本越高越有效。",
    related: ["adverse_selection", "moral_hazard", "mechanism_design"]
  },
  {
    id: "experimental_economics",
    subject: "econ",
    term: "实验经济学",
    en: "Experimental Economics",
    stage: 4,
    cat: "博弈与行为",
    diff: 3,
    def: "用受控实验检验经济理论，观察真实行为而不是只靠假设。",
    example: "随机分组测试不同定价，观察哪组购买率更高。",
    tip: "实验能区分因果，而不仅是相关。",
    related: ["behavioral_economics", "game_theory", "mechanism_design"]
  },
  {
    id: "rational_expectations",
    subject: "econ",
    term: "理性预期",
    en: "Rational Expectations",
    stage: 4,
    cat: "博弈与行为",
    diff: 3,
    def: "人们利用所有可得信息形成对未来的预测，错误不会系统性地重复。",
    example: "央行宣布政策后，市场马上调整预期，政策效果打折。",
    tip: "理性预期让‘预期管理’变得重要。",
    related: ["inflation_expectations", "phillips_curve", "monetary_policy"]
  },
  {
    id: "principal_agent",
    subject: "econ",
    term: "委托代理问题",
    en: "Principal-Agent Problem",
    stage: 4,
    cat: "机制与信息",
    diff: 2,
    def: "代理人替委托人做事，但双方目标不同且信息不对称，代理人可能偷懒或冒险。",
    example: "老板与员工、股东与经理之间都存在委托代理问题。",
    tip: "解决靠激励合同、监督与声誉。",
    related: ["moral_hazard", "information_asymmetry", "mechanism_design"]
  }
];

let CATEGORIES = [...new Set(TERMS.map(t => t.cat))];
const DIFF_LABELS = { 1: "入门", 2: "进阶", 3: "挑战" };
