STAGES.push(
  { id: 101, subject: "math", name: "极限与连续", en: "Limits & Continuity", code: "01", goal: "理解函数在一点附近的趋势，这是微积分的起点。", weeks: "第 1-6 周", color: "#2e6f8f", topics: ["极限", "无穷小", "连续", "夹逼定理"] },
  { id: 102, subject: "math", name: "导数与微分", en: "Derivatives & Differentials", code: "02", goal: "掌握变化率、切线与求导法则。", weeks: "第 7-12 周", color: "#0e7c6b", topics: ["导数", "链式法则", "极值", "泰勒公式"] },
  { id: 103, subject: "math", name: "积分", en: "Integration", code: "03", goal: "从求原函数到计算面积、体积。", weeks: "第 13-18 周", color: "#a97d12", topics: ["不定积分", "定积分", "换元", "分部积分"] },
  { id: 104, subject: "math", name: "级数与多元", en: "Series & Multivariable", code: "04", goal: "进入无穷级数和多元函数的初步分析。", weeks: "第 19-26 周", color: "#c94f2b", topics: ["收敛", "幂级数", "多元函数", "偏导数"] }
);

TERMS.push(
  { id: "limit", subject: "math", term: "极限", en: "Limit", stage: 101, cat: "极限", diff: 1, def: "自变量趋近某值时，函数值趋近的那个确定数值。", example: "x 越来越接近 1 时，f(x)=x+1 越来越接近 2，所以极限是 2。", tip: "极限看趋势，不一定等于该点的函数值。", related: ["infinitesimal", "continuous", "squeeze_theorem"] },
  { id: "infinitesimal", subject: "math", term: "无穷小", en: "Infinitesimal", stage: 101, cat: "极限", diff: 2, def: "极限为 0 的变量，是刻画局部变化的基本工具。", example: "当 x 趋近 0 时，sin(x) 是无穷小。", tip: "无穷小是变量，不是固定的数字 0。", related: ["limit", "squeeze_theorem", "derivative"] },
  { id: "continuous", subject: "math", term: "连续", en: "Continuity", stage: 101, cat: "极限", diff: 1, def: "函数在该点有定义、极限存在，且极限等于函数值。", example: "y=x^2 在每个点都连续，图像没有断口。", tip: "连续是“画图时不用抬笔”。", related: ["limit", "squeeze_theorem", "derivative"] },
  { id: "squeeze_theorem", subject: "math", term: "夹逼定理", en: "Squeeze Theorem", stage: 101, cat: "极限", diff: 2, def: "若一个函数被两个极限相同的函数夹住，则它的极限也相同。", example: "用 x 和 -x 夹住 x·sin(1/x)，可求其趋近 0 的极限。", tip: "先找上下界，再证明两端极限相等。", related: ["limit", "infinitesimal", "continuous"] },
  { id: "derivative", subject: "math", term: "导数", en: "Derivative", stage: 102, cat: "导数", diff: 1, def: "函数在某点的瞬时变化率，即切线斜率。", example: "位移对时间求导得到瞬时速度。", tip: "导数是极限定义的差商。", related: ["limit", "tangent_line", "derivative_rules"] },
  { id: "tangent_line", subject: "math", term: "切线", en: "Tangent Line", stage: 102, cat: "导数", diff: 1, def: "与曲线在该点有相同变化方向的直线，斜率等于导数。", example: "抛物线在某点的切线可以近似替代附近的曲线。", tip: "切线的斜率就是 f'(x)。", related: ["derivative", "differentiability", "derivative_rules"] },
  { id: "differentiability", subject: "math", term: "可微", en: "Differentiability", stage: 102, cat: "导数", diff: 2, def: "函数在该点附近能被线性函数很好逼近的性质。", example: "可微函数一定有切线，但连续函数不一定可微，如尖点。", tip: "可微比连续更强。", related: ["derivative", "tangent_line", "differential"] },
  { id: "derivative_rules", subject: "math", term: "求导法则", en: "Differentiation Rules", stage: 102, cat: "导数", diff: 1, def: "和、差、积、商与复合函数求导的常用公式。", example: "(uv)' = u'v + uv' 就是乘积法则。", tip: "先把式子拆成基础法则，再套公式。", related: ["derivative", "chain_rule", "implicit_derivative"] },
  { id: "chain_rule", subject: "math", term: "链式法则", en: "Chain Rule", stage: 102, cat: "导数", diff: 2, def: "复合函数求导时，外层导数乘以内层导数。", example: "对 sin(x^2) 求导，结果是 cos(x^2)·2x。", tip: "由外到内逐层乘过去。", related: ["derivative_rules", "derivative", "implicit_derivative"] },
  { id: "implicit_derivative", subject: "math", term: "隐函数求导", en: "Implicit Differentiation", stage: 102, cat: "导数", diff: 3, def: "对由方程确定的隐函数两侧同时求导，解出 y'。", example: "x^2+y^2=1 两侧求导可得 y'=-x/y。", tip: "把 y 看成关于 x 的函数，别忘了乘 y'。", related: ["derivative_rules", "chain_rule", "derivative"] },
  { id: "monotonic", subject: "math", term: "单调性", en: "Monotonicity", stage: 102, cat: "应用", diff: 1, def: "函数在区间上始终上升或始终下降的性质。", example: "f'(x)>0 的区间内函数单调递增。", tip: "用导数符号判断升降。", related: ["derivative", "extremum", "inflection"] },
  { id: "extremum", subject: "math", term: "极值", en: "Extremum", stage: 102, cat: "应用", diff: 2, def: "函数在局部范围内取得的最大值或最小值。", example: "抛物线顶点就是局部极值点。", tip: "驻点加上左右导数变号才能确定极值。", related: ["derivative", "monotonic", "inflection"] },
  { id: "inflection", subject: "math", term: "拐点", en: "Inflection Point", stage: 102, cat: "应用", diff: 2, def: "函数凹凸性发生改变的点。", example: "y=x^3 在 x=0 处凹凸性改变，就是拐点。", tip: "二阶导数变号的位置是拐点候选。", related: ["derivative", "monotonic", "extremum"] },
  { id: "lhopital", subject: "math", term: "洛必达法则", en: "L'Hopital's Rule", stage: 102, cat: "极限", diff: 2, def: "0/0 或 ∞/∞ 型极限可转化为分子分母分别求导后的极限。", example: "求 x→0 时 sin(x)/x，可对分子分母求导得 cos(x)/1，极限为 1。", tip: "先判断未定式类型，再使用。", related: ["limit", "derivative", "infinitesimal"] },
  { id: "taylor", subject: "math", term: "泰勒公式", en: "Taylor Series", stage: 102, cat: "级数", diff: 3, def: "用多项式逐阶逼近函数在一点附近的值。", example: "e^x 可以用 1+x+x^2/2!+... 近似。", tip: "阶数越高，逼近越精确。", related: ["derivative", "power_series", "series"] },
  { id: "differential", subject: "math", term: "微分", en: "Differential", stage: 102, cat: "导数", diff: 2, def: "自变量微小变化时，函数值变化的线性近似。", example: "dy=f'(x)dx 是切线上对应的增量。", tip: "微分是近似的线性部分。", related: ["derivative", "differentiability", "tangent_line"] },
  { id: "antiderivative", subject: "math", term: "原函数", en: "Antiderivative", stage: 103, cat: "积分", diff: 1, def: "导数为已知函数的函数。", example: "2x 的原函数是 x^2+C。", tip: "原函数之间相差常数 C。", related: ["indefinite_integral", "definite_integral", "ftc"] },
  { id: "indefinite_integral", subject: "math", term: "不定积分", en: "Indefinite Integral", stage: 103, cat: "积分", diff: 1, def: "求原函数的过程，结果是一族函数。", example: "∫2x dx = x^2+C。", tip: "别忘了积分常数 C。", related: ["antiderivative", "definite_integral", "substitution"] },
  { id: "definite_integral", subject: "math", term: "定积分", en: "Definite Integral", stage: 103, cat: "积分", diff: 1, def: "在区间上对函数求累积量，如面积、路程。", example: "∫₀¹ x dx = 1/2 表示三角形面积。", tip: "定积分得到数值，不定积分得到函数族。", related: ["indefinite_integral", "ftc", "area_volume"] },
  { id: "ftc", subject: "math", term: "微积分基本定理", en: "Fundamental Theorem of Calculus", stage: 103, cat: "积分", diff: 2, def: "把导数与定积分联系起来：积分是微分的逆运算。", example: "先求原函数再代入上下限，即可算定积分。", tip: "基本定理让面积计算变成求原函数。", related: ["definite_integral", "antiderivative", "indefinite_integral"] },
  { id: "substitution", subject: "math", term: "换元积分", en: "Integration by Substitution", stage: 103, cat: "积分", diff: 2, def: "通过变量替换把复杂积分化为简单积分。", example: "∫2x·e^(x^2) dx 可令 u=x^2。", tip: "换元后要记得同时换掉微分。", related: ["indefinite_integral", "integration_by_parts", "definite_integral"] },
  { id: "integration_by_parts", subject: "math", term: "分部积分", en: "Integration by Parts", stage: 103, cat: "积分", diff: 2, def: "由乘积求导法则反推得到的积分方法。", example: "∫x·e^x dx = x·e^x - ∫e^x dx。", tip: "选 u 时优先选容易求导、求导后更简单的部分。", related: ["indefinite_integral", "substitution", "definite_integral"] },
  { id: "improper_integral", subject: "math", term: "反常积分", en: "Improper Integral", stage: 103, cat: "积分", diff: 3, def: "积分区间无穷或函数在区间内无界的积分。", example: "∫₁^∞ 1/x² dx 收敛于 1。", tip: "先取极限再判断是否收敛。", related: ["definite_integral", "convergence", "limit"] },
  { id: "area_volume", subject: "math", term: "面积与体积", en: "Area & Volume", stage: 103, cat: "应用", diff: 2, def: "用定积分计算平面区域面积或旋转体体积。", example: "绕 x 轴旋转的图形体积可用 ∫πf(x)²dx 计算。", tip: "先画图确定积分限，再选对公式。", related: ["definite_integral", "ftc", "improper_integral"] },
  { id: "sequence", subject: "math", term: "数列", en: "Sequence", stage: 104, cat: "级数", diff: 1, def: "按顺序排列的一列数，可以看作定义在正整数上的函数。", example: "1, 1/2, 1/3, ... 是收敛于 0 的数列。", tip: "数列极限是级数收敛的基础。", related: ["convergence", "series", "limit"] },
  { id: "series", subject: "math", term: "级数", en: "Series", stage: 104, cat: "级数", diff: 2, def: "数列各项求和形成的无穷和。", example: "1+1/2+1/4+... 收敛于 2。", tip: "级数是否收敛看部分和数列。", related: ["convergence", "sequence", "power_series"] },
  { id: "convergence", subject: "math", term: "收敛", en: "Convergence", stage: 104, cat: "级数", diff: 2, def: "数列或级数的项趋近于某个有限值。", example: "调和级数发散，而几何级数可收敛。", tip: "判断收敛常用比较、比值、根值等方法。", related: ["series", "sequence", "improper_integral"] },
  { id: "power_series", subject: "math", term: "幂级数", en: "Power Series", stage: 104, cat: "级数", diff: 3, def: "形如 ∑a_n x^n 的级数，可在收敛区间内表示函数。", example: "1/(1-x)=1+x+x²+... 在 |x|<1 时成立。", tip: "收敛半径决定有效范围。", related: ["series", "convergence", "taylor"] },
  { id: "multivariable", subject: "math", term: "多元函数", en: "Multivariable Function", stage: 104, cat: "多元", diff: 2, def: "自变量不止一个的函数。", example: "f(x,y)=x²+y² 是二元函数。", tip: "先固定一部分变量，再逐层分析。", related: ["partial_derivative", "limit", "derivative"] },
  { id: "partial_derivative", subject: "math", term: "偏导数", en: "Partial Derivative", stage: 104, cat: "多元", diff: 2, def: "多元函数对其他变量不变时，对某个变量的导数。", example: "对 f(x,y)=x²y 求 x 的偏导得 2xy。", tip: "求偏导时把其他变量当常数。", related: ["multivariable", "derivative", "tangent_line"] }
);
